export const onDemandDetailsContentSetDetailsData = {
  data: [
    {
      cmodNo: 1,
      setNo: 1,
      name: 'Content Set 1',
      matchTypeNo: 1,
      matchTypeText: 'Match Any',
      origSetNo: 1,
    },
    {
      cmodNo: 2,
      setNo: 1,
      name: 'Content Set 1',
      matchTypeNo: 1,
      matchTypeText: 'Match Any',
      origSetNo: 1,
    },
    {
      cmodNo: 3,
      setNo: 1,
      name: 'Content Set 1',
      matchTypeNo: 1,
      matchTypeText: 'Match Any',
      origSetNo: 1,
    },
    {
      cmodNo: 4,
      setNo: 1,
      name: 'Content Set 1',
      matchTypeNo: 1,
      matchTypeText: 'Match Any',
      origSetNo: 1,
    },
    {
      cmodNo: 5,
      setNo: 1,
      name: 'Content Set 1',
      matchTypeNo: 1,
      matchTypeText: 'Match Any',
      origSetNo: 1,
    },
    {
      cmodNo: 6,
      setNo: 1,
      name: 'Content Set 1',
      matchTypeNo: 1,
      matchTypeText: 'Match Any',
      origSetNo: 1,
    },
  ],
  totalCount: 6,
  filteredCount: 6,
  totalPages: 1,
  currentPage: 0,
  pageSize: 100,
  focusFound: false,
  focusPage: 0,
  warnings: [],
};
