export const onDemandDetailsAdSpaceData = {
  data: [
    {
      adspNo: 242,
      name: 'TVVOD_PREROLL_SPONSORSHIP',
      cmodNo: 1,
      sareNo: 0,
      imprTotAct: 0,
      imprActDate: 0,
      imprActTime: 0,
    },
    {
      adspNo: 242,
      name: 'TVVOD_PREROLL_SPONSORSHIP',
      cmodNo: 2,
      sareNo: 0,
      imprTotAct: 0,
      imprActDate: 0,
      imprActTime: 0,
    },
    {
      adspNo: 242,
      name: 'TVVOD_PREROLL_SPONSORSHIP',
      cmodNo: 3,
      sareNo: 0,
      imprTotAct: 0,
      imprActDate: 0,
      imprActTime: 0,
    },
    {
      adspNo: 242,
      name: 'TVVOD_PREROLL_SPONSORSHIP',
      cmodNo: 4,
      sareNo: 0,
      imprTotAct: 0,
      imprActDate: 0,
      imprActTime: 0,
    },
    {
      adspNo: 242,
      name: 'TVVOD_PREROLL_SPONSORSHIP',
      cmodNo: 5,
      sareNo: 0,
      imprTotAct: 0,
      imprActDate: 0,
      imprActTime: 0,
    },
    {
      adspNo: 242,
      name: 'TVVOD_PREROLL_SPONSORSHIP',
      cmodNo: 6,
      sareNo: 0,
      imprTotAct: 0,
      imprActDate: 0,
      imprActTime: 0,
    },
    {
      adspNo: 244,
      name: 'TVVOD_MIDROLL_SPONSORSHIPOUT',
      cmodNo: 1,
      sareNo: 0,
      imprTotAct: 0,
      imprActDate: 0,
      imprActTime: 0,
    },
    {
      adspNo: 244,
      name: 'TVVOD_MIDROLL_SPONSORSHIPOUT',
      cmodNo: 2,
      sareNo: 0,
      imprTotAct: 0,
      imprActDate: 0,
      imprActTime: 0,
    },
    {
      adspNo: 244,
      name: 'TVVOD_MIDROLL_SPONSORSHIPOUT',
      cmodNo: 3,
      sareNo: 0,
      imprTotAct: 0,
      imprActDate: 0,
      imprActTime: 0,
    },
    {
      adspNo: 244,
      name: 'TVVOD_MIDROLL_SPONSORSHIPOUT',
      cmodNo: 4,
      sareNo: 0,
      imprTotAct: 0,
      imprActDate: 0,
      imprActTime: 0,
    },
    {
      adspNo: 244,
      name: 'TVVOD_MIDROLL_SPONSORSHIPOUT',
      cmodNo: 5,
      sareNo: 0,
      imprTotAct: 0,
      imprActDate: 0,
      imprActTime: 0,
    },
    {
      adspNo: 245,
      name: 'TVVOD_MIDROLL_SPONSORSHIPIN',
      cmodNo: 1,
      sareNo: 0,
      imprTotAct: 0,
      imprActDate: 0,
      imprActTime: 0,
    },
    {
      adspNo: 245,
      name: 'TVVOD_MIDROLL_SPONSORSHIPIN',
      cmodNo: 2,
      sareNo: 0,
      imprTotAct: 0,
      imprActDate: 0,
      imprActTime: 0,
    },
    {
      adspNo: 245,
      name: 'TVVOD_MIDROLL_SPONSORSHIPIN',
      cmodNo: 3,
      sareNo: 0,
      imprTotAct: 0,
      imprActDate: 0,
      imprActTime: 0,
    },
    {
      adspNo: 245,
      name: 'TVVOD_MIDROLL_SPONSORSHIPIN',
      cmodNo: 4,
      sareNo: 0,
      imprTotAct: 0,
      imprActDate: 0,
      imprActTime: 0,
    },
    {
      adspNo: 245,
      name: 'TVVOD_MIDROLL_SPONSORSHIPIN',
      cmodNo: 5,
      sareNo: 0,
      imprTotAct: 0,
      imprActDate: 0,
      imprActTime: 0,
    },
    {
      adspNo: 245,
      name: 'TVVOD_MIDROLL_SPONSORSHIPIN',
      cmodNo: 6,
      sareNo: 0,
      imprTotAct: 0,
      imprActDate: 0,
      imprActTime: 0,
    },
    {
      adspNo: 248,
      name: 'TVVOD_POSTROLL_SPONSORSHIP',
      cmodNo: 1,
      sareNo: 0,
      imprTotAct: 0,
      imprActDate: 0,
      imprActTime: 0,
    },
    {
      adspNo: 248,
      name: 'TVVOD_POSTROLL_SPONSORSHIP',
      cmodNo: 2,
      sareNo: 0,
      imprTotAct: 0,
      imprActDate: 0,
      imprActTime: 0,
    },
    {
      adspNo: 248,
      name: 'TVVOD_POSTROLL_SPONSORSHIP',
      cmodNo: 3,
      sareNo: 0,
      imprTotAct: 0,
      imprActDate: 0,
      imprActTime: 0,
    },
    {
      adspNo: 248,
      name: 'TVVOD_POSTROLL_SPONSORSHIP',
      cmodNo: 4,
      sareNo: 0,
      imprTotAct: 0,
      imprActDate: 0,
      imprActTime: 0,
    },
    {
      adspNo: 248,
      name: 'TVVOD_POSTROLL_SPONSORSHIP',
      cmodNo: 5,
      sareNo: 0,
      imprTotAct: 0,
      imprActDate: 0,
      imprActTime: 0,
    },
    {
      adspNo: 248,
      name: 'TVVOD_POSTROLL_SPONSORSHIP',
      cmodNo: 6,
      sareNo: 0,
      imprTotAct: 0,
      imprActDate: 0,
      imprActTime: 0,
    },
  ],
  totalCount: 23,
  filteredCount: 23,
  totalPages: 1,
  currentPage: 0,
  pageSize: 100,
  focusFound: false,
  focusPage: 0,
  warnings: [],
};
